### ISSUE TITLE
执行 python syncnet.py 时报错

### ISSUE THREAD

**Issue by szdguai** [anliyuan/Ultralight-Digital-Human#105]
在 WSL 上执行的
(dh) sdd@DESKTOP-ACPHA5T:~/test/Ultralight-Digital-Human$ python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir /home/sdd/test/Ultralight-Digital-Human/vedio/ --asr hubert
Traceback (most recent call last):
  File "/home/sdd/test/Ultralight-Digital-Human/syncnet.py", line 258, in <module>
    train(opt.save_dir, opt.dataset_dir, opt.asr)
  File "/home/sdd/test/Ultralight-Digital-Human/syncnet.py", line 229, in train
    for batch in train_data_loader:
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sdd/anaconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sdd/test/Ultralight-Digital-Human/syncnet.py", line 89, in __getitem__
    img_ex = cv2.imread(self.img_path_list[ex_int])
IndexError: list index out of range

**Comment by whisky-12** [comment]
同样的问题 ，请问大佬解决了嘛

**Comment by anliyuan** [comment]
你的图片比音频特征多吧  调整一下

**Comment by danny-zhu** [comment]
我也遇到同样的问题，数据目录下有aud_hu.py  aud.wav full_body_img文件夹和landmarks文件夹，full_body_img和landmarks里的文件数量一样的
