### ISSUE TITLE
如何解决报错捏

### ISSUE THREAD

**Issue by qiqi0308** [anliyuan/Ultralight-Digital-Human#110]
在训练数字人模型时，报错返回如下
E:\main_project\Ultralight-Digital-Human-master>python train.py --dataset_dir ./data_dir/ --save_dir ./checkpoint/ --asr hubert --use_syncnet --syncnet_checkpoint 5.pth
E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
./data_dir/
(4613, 2, 1024)
4614
Epoch 1/200:   0%|                                                                           | 0/4612 [00:00<?, ?img/s]E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\nn\functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Epoch 1/200:   2%|▉                                             | 96/4612 [00:40<31:24,  2.40img/s, loss (batch)=0.465]
Traceback (most recent call last):
  File "E:\main_project\Ultralight-Digital-Human-master\train.py", line 141, in <module>
    train(net, args.epochs, args.batchsize, args.lr)
  File "E:\main_project\Ultralight-Digital-Human-master\train.py", line 96, in train
    for batch in train_dataloader:
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\main_project\Ultralight-Digital-Human-master\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\main_project\Ultralight-Digital-Human-master\datasetsss.py", line 133, in __getitem__
    img_concat_T, img_real_T = self.process_img(img, lms_path, img_ex, lms_path_ex)
  File "E:\main_project\Ultralight-Digital-Human-master\datasetsss.py", line 111, in process_img
    crop_img = cv2.resize(crop_img, (168, 168), cv2.INTER_AREA)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by lordlxh** [comment]
训练视频中有一些帧没有检测到人脸
