### ISSUE TITLE
在process.py的时候，提示get_landmark.py中IndexError: list index out of range

### ISSUE THREAD

**Issue by Semonxue** [anliyuan/Ultralight-Digital-Human#22]
视频是25fps的，看landmarks目录，输出到full_body_img目录中图片的一半左右，内存也没有爆，屡试不爽。
```
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '/root/autodl-tmp/yangshi001/aud.wav':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    ISFT            : Lavf58.76.100
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 pcm_s16le
size=    4407kB time=00:02:21.03 bitrate= 256.0kbits/s speed=1.02e+03x    
video:0kB audio:4407kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001728%
[INFO] ===== extracted audio =====
extracting images...
detecting landmarks...
Traceback (most recent call last):
  File "/root/autodl-tmp/Ultralight-Digital-Human/data_utils/process.py", line 82, in <module>
    get_landmark(opt.path, landmarks_dir)
  File "/root/autodl-tmp/Ultralight-Digital-Human/data_utils/process.py", line 57, in get_landmark
    pre_landmark, x1, y1 = landmark.detect(img_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Ultralight-Digital-Human/data_utils/get_landmark.py", line 90, in detect
    cropped = cropped_imgs[0]
              ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by Semonxue** [comment]
源视频是1080想080的，所以报错，换成720x720之后就过了。

**Comment by anliyuan** [comment]
按道理说跟分辨率没关系，这块儿代码是陈年旧代码，回头优化一下。

**Comment by harrison11111** [comment]
File "/media/hdd2t/Works/Ultralight-Digital-Human/data_utils/get_landmark.py", line 92, in detect
    cropped = cropped_imgs[0]
我也出现这个问题，感觉像是没识别face导致没有图像，按照下面修改直接跳过
--- a/data_utils/get_landmark.py
+++ b/data_utils/get_landmark.py
@@ -19,6 +19,8 @@ def face_det(img, model):
     alpha_list = []
     height, width = img.shape[:2]
     bboxes, indices, kps = model.detect(img)
+#    print(f"bboxes:{bboxes}")
+#    print(f"indices:{indices}")

     for i in indices:
         x1, y1, x2, y2 = int(bboxes[i, 0]), int(bboxes[i, 1]), int(bboxes[i, 0] + bboxes[i, 2]), int(bboxes[i, 1] + bboxes[i, 3])
@@ -87,6 +89,9 @@ class Landmark:

         h,w = img_ori.shape[:2]
         cropped_imgs, boxes_list, center_list, alpha_list = face_det(img, self.det_net)
+        if cropped_imgs is None or len(cropped_imgs) <= 0:
+            return None,0,0
+
         cropped = cropped_imgs[0]
         # cv2.imshow("cropped", cropped)
         h,w = cropped.shape[:2]
@@ -112,4 +117,4 @@ class Landmark:
         pre_landmark[:,1] *= h
         pre_landmark = pre_landmark.astype(np.int32)
         return pre_landmark, x1, y1
-
\ No newline at end of file
+
diff --git a/data_utils/process.py b/data_utils/process.py
index d7410bb..f8a165a 100644
--- a/data_utils/process.py
+++ b/data_utils/process.py
@@ -21,6 +21,7 @@ def extract_images(path, mode):
     cap = cv2.VideoCapture(path)
     fps = cap.get(cv2.CAP_PROP_FPS)
     if mode == "hubert" and fps != 25:
+        print(f"video fps:{fps}")
         raise ValueError("Using hubert,your video fps should be 25!!!")
     if mode == "wenet" and fps != 20:
         raise ValueError("Using wenet,your video fps should be 20!!!")
@@ -55,6 +56,10 @@ def get_landmark(path, landmarks_dir):
         img_path = os.path.join(full_img_dir, img_name)
         lms_path = os.path.join(landmarks_dir, img_name.replace(".jpg", ".lms"))
         pre_landmark, x1, y1 = landmark.detect(img_path)
+        if pre_landmark is None:
+            print(f"landmark is none")
+            continue
+
         with open(lms_path, "w") as f:
             for p in pre_landmark:
                 x, y = p[0]+x1, p[1]+y1
