### ISSUE TITLE
windows下运行python process.py D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\1021.mp4 --asr hubert出现ImportError: cannot import name 'wait3' from 'os' (D:\anaconda3\envs\udh\lib\os.py)

### ISSUE THREAD

**Issue by Watermelon001** [anliyuan/Ultralight-Digital-Human#23]
请问大佬出现这个是我缺啥了吗，下面是完整
(udh) D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\data_utils>python process.py D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\1021.mp4 --asr hubert
[INFO] ===== extract audio from D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\1021.mp4 to D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\aud.wav =====
ffmpeg version 2024-10-10-git-0f5592cfc7-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 42.100 / 59. 42.100
  libavcodec     61. 22.100 / 61. 22.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.100 / 10.  6.100
  libswscale      8.  5.100 /  8.  5.100
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000015db3d37c00] Unknown cover type: 0x1.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\1021.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2024-10-21T07:33:39.000000Z
    Hw              : 1
    bitrate         : 22000000
    maxrate         : 0
    te_is_reencode  : 1
    encoder         : Lavf61.1.100
  Duration: 00:05:02.92, start: 0.000000, bitrate: 17744 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2160x3840 [SAR 1:1 DAR 9:16], 17546 kb/s, 25 fps, 25 tbr, 25 tbn (default)
    Metadata:
      creation_time   : 2024-10-21T07:33:39.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2024-10-21T07:33:39.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\train\aud.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    te_is_reencode  : 1
    Hw              : 1
    bitrate         : 22000000
    maxrate         : 0
    ISFT            : Lavf61.9.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, stereo, s16, 512 kb/s (default)
    Metadata:
      encoder         : Lavc61.22.100 pcm_s16le
      creation_time   : 2024-10-21T07:33:39.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/wav @ 0000015db435ee40] video:0KiB audio:18932KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.000402%
size=   18932KiB time=00:05:02.90 bitrate= 512.0kbits/s speed=1.46e+03x
[INFO] ===== extracted audio =====
extracting images...
detecting landmarks...
Traceback (most recent call last):
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\data_utils\process.py", line 82, in <module>
    get_landmark(opt.path, landmarks_dir)
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\data_utils\process.py", line 49, in get_landmark
    from get_landmark import Landmark
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\data_utils\get_landmark.py", line 2, in <module>
    from os import wait3
ImportError: cannot import name 'wait3' from 'os' (D:\anaconda3\envs\udh\lib\os.py)

**Comment by anliyuan** [comment]
from os import wait3
把这行删了就行了。

**Comment by Watermelon001** [comment]
感谢大佬，解决了😁😁😁

**Comment by Watermelon001** [comment]
请问大佬，python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir ./data_dir/ --asr hubert这里的data_dir没有这个文件，是需要改为data_utils吗？

**Comment by Watermelon001** [comment]
因为报错
(udh) D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master>python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir ./data_dir/ --asr hubert
Traceback (most recent call last):
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\syncnet.py", line 259, in <module>
    train(opt.save_dir, opt.dataset_dir, opt.asr)
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\syncnet.py", line 222, in train
    train_dataset = Dataset(dataset_dir, mode=mode)
  File "D:\SZR\Ultralight-Digital-Human\Ultralight-Digital-Human-master\syncnet.py", line 20, in __init__
    for i in range(len(os.listdir(dataset_dir+"/full_body_img/"))):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './data_dir//full_body_img/'
我看full_body_img文件夹在data_utils里

**Comment by anliyuan** [comment]
> 请问大佬，python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir ./data_dir/ --asr hubert这里的data_dir没有这个文件，是需要改为data_utils吗？

这个地方需要写你自己数据集的目录

**Comment by Watermelon001** [comment]
噢噢噢，好的好的，我去改一改😢

**Comment by sdfcyin2025** [comment]
请问大佬，最后一行的错误是权限问题吧。win10系统，在这个syncnet_ckpt文件夹属性中已经添加了用户控制权限，还是这个报错信息。不知如何处理了。

(dh) E:\Digital Human\Ultralight-Digital-Human>python train.py --dataset_dir ./data_dir/ --save_dir ./checkpoint/ --asr hubert --use_syncnet --syncnet_checkpoint syncnet_ckpt
D:\anaconda3\envs\dh\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\anaconda3\envs\dh\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to C:\Users\P520PC/.cache\torch\hub\checkpoints\vgg19-dcbb9e9d.pth
100%|███████████████████████████████████████████████████████████████████████████████| 548M/548M [01:36<00:00, 5.93MB/s]
Traceback (most recent call last):
  File "E:\Digital Human\Ultralight-Digital-Human\train.py", line 140, in <module>
    train(net, args.epochs, args.batchsize, args.lr)
  File "E:\Digital Human\Ultralight-Digital-Human\train.py", line 73, in train
    syncnet.load_state_dict(torch.load(args.syncnet_checkpoint))
  File "D:\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'syncnet_ckpt'
