### ISSUE TITLE
尝试wenet时报错

### ISSUE THREAD

**Issue by qwert1887** [anliyuan/Ultralight-Digital-Human#31]
感谢作者大大的伟大工作，我在尝试用wenet训练syncnet时报错如下，请问是我哪里处理错了么：
`
python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir dataset/video_20fps/ --asr wenet
`
```
Traceback (most recent call last):
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 259, in <module>
    train(opt.save_dir, opt.dataset_dir, opt.asr)
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 230, in train
    for batch in train_data_loader:
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 99, in __getitem__
    audio_feat = audio_feat.reshape(32,32,32)
RuntimeError: shape '[32, 32, 32]' is invalid for input of size 131072

```
此外，可以问下`pth2onnx.py`的用法么，我尝试转化最终的195.pth时报错如下：
```
Traceback (most recent call last):
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/pth2onnx.py", line 36, in <module>
    torch_out = net(img, audio)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 206, in forward
    audio_feat  = self.audio_model(audio_feat)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 154, in forward
    x = self.conv1(x)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 36, in forward
    return self.conv(x)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 32, 1, 1], expected input[1, 128, 16, 32] to have 32 channels, but got 128 channels instead

```

**Comment by anliyuan** [comment]
哦哦这两个地方忘记加判断条件了。。可以先自行修改一下，syncnet把报错这行注释掉，上面那行注释放开。
pth2onnx里面也是需要改一下audio_feature的形状。回头我修改一下。感谢提bug

**Comment by gushuaialan1** [comment]
> audio_feat = audio_feat.reshape(32,32,32)
> RuntimeError: shape '[32, 32, 32]' is invalid for in

实测可能应该reshape到128,32,32

**Comment by qwert1887** [comment]
用wenet跑通了训练，如大佬所提到的，效果的确没有比hubert强，还没来得及进行其他对比。pth2onnx还没改

**Comment by anliyuan** [comment]
> 用wenet跑通了训练，如大佬所提到的，效果的确没有比hubert强，还没来得及进行其他对比。pth2onnx还没改
wenet可以用于移动端，效果也是可接受的。

**Comment by drq123456** [comment]
> 哦哦这两个地方忘记加判断条件了。。可以先自行修改一下，syncnet把报错这行注释掉，上面那行注释放开。 pth2onnx里面也是需要改一下audio_feature的形状。回头我修改一下。感谢提bug

Traceback (most recent call last):
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 258, in <module>
    audio_embedding, face_embedding = syncnet(img, audio)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 202, in forward
    audio_embedding = self.audio_encoder(audio_sequences)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 116, in forward
    out = self.conv_block(x)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/orangepi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 128, 3, 3], expected input[1, 16, 32, 32] to have 128 channels, but got 16 channels instead



I followed the instructions to remove the comments, but I'm still getting an error.

**Comment by drq123456** [comment]
> 用wenet跑通了训练，如大佬所提到的，效果的确没有比hubert强，还没来得及进行其他对比。pth2onnx还没改

Hello, how did you modify it in the end?


 audio_feat = audio_feat.reshape(128,16,32)
        #audio_feat = audio_feat.reshape(32,32,32)

**Comment by drq123456** [comment]
> 哦哦这两个地方忘记加判断条件了。。可以先自行修改一下，syncnet把报错这行注释掉，上面那行注释放开。 pth2onnx里面也是需要改一下audio_feature的形状。回头我修改一下。感谢提bug

 audio_feat = audio_feat.reshape(128,16,32)
        #audio_feat = audio_feat.reshape(32,32,32)我把注释放开 发现还是报错
        RuntimeError: shape '[128, 16, 32]' is invalid for input of size 131072

**Comment by Boom199801** [comment]
> 感谢作者大大的伟大工作，我在尝试用wenet训练syncnet时报错如下，请问是我哪里处理错了么： `python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir dataset/video_20fps/ --asr wenet`
> 
> ```
> Traceback (most recent call last):
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 259, in <module>
>     train(opt.save_dir, opt.dataset_dir, opt.asr)
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 230, in train
>     for batch in train_data_loader:
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
>     data = self._next_data()
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
>     return self._process_data(data)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
>     data.reraise()
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
>     raise exception
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/syncnet.py", line 99, in __getitem__
>     audio_feat = audio_feat.reshape(32,32,32)
> RuntimeError: shape '[32, 32, 32]' is invalid for input of size 131072
> ```
> 
> 此外，可以问下`pth2onnx.py`的用法么，我尝试转化最终的195.pth时报错如下：
> 
> ```
> Traceback (most recent call last):
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/pth2onnx.py", line 36, in <module>
>     torch_out = net(img, audio)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 206, in forward
>     audio_feat  = self.audio_model(audio_feat)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 154, in forward
>     x = self.conv1(x)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/gs/PycharmProjects/Ultralight-Digital-Human/unet.py", line 36, in forward
>     return self.conv(x)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
>     input = module(input)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/gs/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [64, 32, 1, 1], expected input[1, 128, 16, 32] to have 32 channels, but got 128 channels instead
> ```

你好大佬，可以提供一下20fps的视频吗，我这边使用25fps转成20fps后跑process.py报错

**Comment by qwert1887** [comment]
只要是ffmpeg转的20fps素材应该都没有问题，主要还是音频处理那段逻辑需要修改和判断。我上次跑通了，还没有整理，整理后提个PR

**Comment by anliyuan** [comment]
已修复 可以再试一次
