### ISSUE TITLE
小白请教：IsADirectoryError: [Errno 21] Is a directory: './syncnet_ckpt/'

### ISSUE THREAD

**Issue by do-one-thing-to-well** [anliyuan/Ultralight-Digital-Human#32]
按照README.md的步骤，在**train**阶段，`找一个loss最低的checkpoint来训练数字人模型`这里，执行如下命令报错：
```shell
python train.py --dataset_dir ./res/ --save_dir ./checkpoint/ --asr hubert --use_syncnet --syncnet_checkpoint ./syncnet_ckpt/
```

报错信息如下：
```shell
Traceback (most recent call last):
  File "/home/xxx/data/xxx/Ultralight-Digital-Human/train.py", line 141, in <module>
    train(net, args.epochs, args.batchsize, args.lr)
  File "/home/xxx/data/xxx/Ultralight-Digital-Human/train.py", line 73, in train
    syncnet.load_state_dict(torch.load(args.syncnet_checkpoint))
  File "/home/xxx/miniconda3/envs/udh/lib/python3.10/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xxx/miniconda3/envs/udh/lib/python3.10/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xxx/miniconda3/envs/udh/lib/python3.10/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: './syncnet_ckpt/'
```

这里我是不是应该需要修改源码，增加对`syncnet_ckpt`这个目录的类型判断？还是有其他的解决办法？

**Comment by do-one-thing-to-well** [comment]
我上一步执行的命令是：
```shell
python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir ./res/ --asr hubert
```
那训练syncnet得到的权重路径是不是就是这个  **`./syncnet_ckpt/`** 了？
如果是，我也试了，还是报错，报错信息如题。
如果不是，那请问你说的权重路径是哪个？谢谢了。

**Comment by do-one-thing-to-well** [comment]
我后来试了，根据【训练`syncnet`】时候传入的路径，我在【loss最低的checkpoint】时，执行了如下命令：
```shell
python train.py --dataset_dir ./res/ --save_dir ./checkpoint/ --asr hubert --use_syncnet --syncnet_checkpoint  ./syncnet_ckpt/1.pth
```
这样好像就可以了。。。

**Comment by do-one-thing-to-well** [comment]
> 我后来试了，根据【训练`syncnet`】时候传入的路径，我在【loss最低的checkpoint】时，执行了如下命令：
> 
> ```shell
> python train.py --dataset_dir ./res/ --save_dir ./checkpoint/ --asr hubert --use_syncnet --syncnet_checkpoint  ./syncnet_ckpt/1.pth
> ```
> 
> 这样好像就可以了。。。

大佬，，我这个方式对不对，如果对的话，我就关闭Issue了。

**Comment by danny-zhu** [comment]
可能是笔误，把datasetsss.py中第34行的 if self.audio_feats[0]<len(self.img_path_list) 改成 if self.audio_feats.shape[0]<len(self.img_path_list)
