### ISSUE TITLE
wenet

### ISSUE THREAD

**Issue by drq123456** [anliyuan/Ultralight-Digital-Human#36]
python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir /home/orangepi/metahumanvideo --asr wenet 
Traceback (most recent call last):
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 260, in <module>
    train(opt.save_dir, opt.dataset_dir, opt.asr)
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 237, in train
    loss = cosine_loss(audio_embedding, face_embedding, y)
  File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 214, in cosine_loss
    d = nn.functional.cosine_similarity(a, v)
RuntimeError: The size of tensor a (10752) must match the size of tensor b (4608) at non-singleton dimension 1

Could you please provide more context or details about the error you're encountering?

**Comment by zemooo7** [comment]
same

**Comment by anliyuan** [comment]
> python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir /home/orangepi/metahumanvideo --asr wenet Traceback (most recent call last): File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 260, in train(opt.save_dir, opt.dataset_dir, opt.asr) File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 237, in train loss = cosine_loss(audio_embedding, face_embedding, y) File "/home/orangepi/Ultralight-Digital-Human-master/syncnet.py", line 214, in cosine_loss d = nn.functional.cosine_similarity(a, v) RuntimeError: The size of tensor a (10752) must match the size of tensor b (4608) at non-singleton dimension 1
> 
> Could you please provide more context or details about the error you're encountering?

周末看一下怎么回事

**Comment by zemooo7** [comment]
首先是在`wenet_infer.py`
```
Traceback (most recent call last):
  File "/home/hua/hzh/TalkingHead/Ultralight-Digital-Human/data_utils/wenet_infer.py", line 501, in <module>
    waveform = np.concatenate([empty_audio_30, waveform, empty_audio_31], axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
```
我就把你在`wenet_infer.py, line 496`的注释 `# stream = stream[:,0]` 给放开了

![2024-11-01 10-35-46 的屏幕截图](https://github.com/user-attachments/assets/f3983adf-7b63-40e2-b9a4-eb9f5f4f9187)
接着运行`python syncnet.py --save_dir ./syncnet_ckpt/ --dataset_dir ./data_dir/ --asr wenet`
```
  File "/home/hua/hzh/TalkingHead/Ultralight-Digital-Human/syncnet.py", line 99, in __getitem__
    audio_feat = audio_feat.reshape(32,32,32)
RuntimeError: shape '[32, 32, 32]' is invalid for input of size 131072
```
改为`(128,16,32)`也有错误，`RuntimeError: shape '[128, 16, 32]' is invalid for input of size 131072`
看了issue的建议改为`(128,32,32)`后，就有了这个错误
```
Traceback (most recent call last):
  File "/home/hua/hzh/TalkingHead/Ultralight-Digital-Human/syncnet.py", line 259, in <module>
    train(opt.save_dir, opt.dataset_dir, opt.asr)
  File "/home/hua/hzh/TalkingHead/Ultralight-Digital-Human/syncnet.py", line 236, in train
    loss = cosine_loss(audio_embedding, face_embedding, y)
  File "/home/hua/hzh/TalkingHead/Ultralight-Digital-Human/syncnet.py", line 213, in cosine_loss
    d = nn.functional.cosine_similarity(a, v)
RuntimeError: The size of tensor a (10752) must match the size of tensor b (4608) at non-singleton dimension 1
```

**Comment by danielzang** [comment]
same

**Comment by Boom199801** [comment]
遇到了同样的问题@anliyuan

**Comment by anliyuan** [comment]
应该没问题了 再试一次吧

**Comment by drq123456** [comment]
> 应该没问题了 再试一次吧

感谢作者大大，我马上去试试
