### ISSUE TITLE
在使用hubert报错了,大佬帮忙看看什么原因

### ISSUE THREAD

**Issue by swd1221** [anliyuan/Ultralight-Digital-Human#52]
(dh) D:\MyWork\dh\Ultralight-Digital-Human-master\data_utils>python process.py D:\MyWork\dh\mp4\375205664-9d0b37ee-2076-4b4f-93ba-eb939a9fb427.mp4 --asr hubert
[INFO] ===== extract audio from D:\MyWork\dh\mp4\375205664-9d0b37ee-2076-4b4f-93ba-eb939a9fb427.mp4 to D:\MyWork\dh\mp4\aud.wav =====
ffmpeg version 2024-11-03-git-df00705e00-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 46.100 / 59. 46.100
  libavcodec     61. 24.100 / 61. 24.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.101 / 10.  6.101
  libswscale      8.  9.101 /  8.  9.101
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\MyWork\dh\mp4\375205664-9d0b37ee-2076-4b4f-93ba-eb939a9fb427.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 00:01:00.45, start: 0.000000, bitrate: 1219 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 1280x720, 1157 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 57 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'D:\MyWork\dh\mp4\aud.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf61.9.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)
    Metadata:
      encoder         : Lavc61.24.100 pcm_s16le
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/wav @ 00000170507d9740] video:0KiB audio:1890KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.004030%
size=    1890KiB time=00:01:00.48 bitrate= 256.0kbits/s speed=2.28e+03x
[INFO] ===== extracted audio =====
extracting images...
detecting landmarks...
C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\cuda\__init__.py:88: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "D:\MyWork\dh\Ultralight-Digital-Human-master\data_utils\process.py", line 82, in <module>
    get_landmark(opt.path, landmarks_dir)
  File "D:\MyWork\dh\Ultralight-Digital-Human-master\data_utils\process.py", line 50, in get_landmark
    landmark = Landmark()
  File "D:\MyWork\dh\Ultralight-Digital-Human-master\data_utils\get_landmark.py", line 78, in __init__
    checkpoint = torch.load('./checkpoint_epoch_335.pth.tar')
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\XZ-BJB006\anaconda3\envs\dh\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by anliyuan** [comment]
电脑上没cuda或装环境时候没有装cuda支持。
