### ISSUE TITLE
在执行inference.py时报错

### ISSUE THREAD

**Issue by drq123456** [anliyuan/Ultralight-Digital-Human#66]
(dh) (base) root@autodl-container-2d0241b899-289114e4:~/Ultralight-Digital-Human-master# python inference.py --asr wenet --dataset /root/metahumanvideo --audio_feat /root/metahumanvideo/aud_wenet.npy --save_path 1.mp4 --checkpoint /root/Ultralight-Digital-Human-master/syncnet_ckpt/39.pth
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "/root/Ultralight-Digital-Human-master/inference.py", line 64, in <module>
    net.load_state_dict(torch.load(checkpoint))
  File "/root/miniconda3/envs/dh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
请问大家遇到过这种报错吗，我在执行inference.py文件推理时遇到的错误，求助

**Comment by anliyuan** [comment]
inference时候为什么要加载syncnet的模型啊

**Comment by 18595071403** [comment]
如果运行：python inference.py  --asr  hubert  --dataset  ./data_utils/  --audio_feat  kk_hu.npy  --save_path  kk.mp4   --checkpoint  ./checkpoint/195.pth
**命令不报错这个：OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'**
只需要把infernce.py中
if mode=="hubert":
    video_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc('M','J','P', 'G'), 25, (w, h))
if mode=="wenet":
    video_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc('M','J','P', 'G'), 20, (w, h))

修改为
if mode=="hubert":
    video_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc('m','p','4', 'v'), 25, (w, h))
if mode=="wenet":
    video_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc('M','J','P', 'G'), 20, (w, h))
    希望对你们跑通有所帮助
