### ISSUE TITLE
使用hubert提取音频特征时报错

### ISSUE THREAD

**Issue by wangzai23333** [anliyuan/Ultralight-Digital-Human#84]
python process.py I:\GitHub\Ultralight-Digital-Human\aa54ca97a40d02e3ad25966870b7753a.mp4  --asr hubert
[INFO] ===== extract audio from I:\GitHub\Ultralight-Digital-Human\aa54ca97a40d02e3ad25966870b7753a.mp4 to I:\GitHub\Ultralight-Digital-Human\aud.wav =====
ffmpeg version N-111814-g9f66286f0b-20230825 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --disable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --disable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230825
  libavutil      58. 17.100 / 58. 17.100
  libavcodec     60. 23.100 / 60. 23.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'I:\GitHub\Ultralight-Digital-Human\aa54ca97a40d02e3ad25966870b7753a.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:08.29, start: 0.000000, bitrate: 989 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 720x1280, 784 kb/s, SAR 1:1 DAR 9:16, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 199 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File 'I:\GitHub\Ultralight-Digital-Human\aud.wav' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'I:\GitHub\Ultralight-Digital-Human\aud.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf60.10.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, stereo, s16, 512 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.23.100 pcm_s16le
[out#0/wav @ 0000019e4ab58140] video:0kB audio:518kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.014702%
size=     518kB time=00:00:08.28 bitrate= 512.1kbits/s speed= 447x
[INFO] ===== extracted audio =====
extracting images...
detecting landmarks...
Traceback (most recent call last):
  File "process.py", line 82, in <module>
    get_landmark(opt.path, landmarks_dir)
  File "process.py", line 57, in get_landmark
    pre_landmark, x1, y1 = landmark.detect(img_path)
  File "I:\GitHub\Ultralight-Digital-Human\data_utils\get_landmark.py", line 88, in detect
    cropped_imgs, boxes_list, center_list, alpha_list = face_det(img, self.det_net)
  File "I:\GitHub\Ultralight-Digital-Human\data_utils\get_landmark.py", line 20, in face_det
    bboxes, indices, kps = model.detect(img)
  File "I:\GitHub\Ultralight-Digital-Human\data_utils\detect_face.py", line 80, in detect
    bboxes = self.distance2bbox(anchor_centers, bbox_preds)
  File "I:\GitHub\Ultralight-Digital-Human\data_utils\detect_face.py", line 36, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
ValueError: operands could not be broadcast together with shapes (12800,) (3200,)

**Comment by wangzai23333** [comment]
请问怎么解决

**Comment by JXLee1999** [comment]
修改opencv版本 要用最新的
