### ISSUE TITLE
python process.py video/me25.mp4 --asr hubert【cv2.error: OpenCV(4.10.0)】

### ISSUE THREAD

**Issue by mikestut** [anliyuan/Ultralight-Digital-Human#96]
detecting landmarks...
[ERROR:0@18.866] global onnx_importer.cpp:1035 handleNode DNN/ONNX: ERROR during processing node with 5 inputs and 1 outputs: [Slice]:(onnx_node!Slice_25) from domain='ai.onnx'
Traceback (most recent call last):
  File "/home/tyn/Ultralight-Digital-Human/data_utils/process.py", line 82, in <module>
    get_landmark(opt.path, landmarks_dir)
  File "/home/tyn/Ultralight-Digital-Human/data_utils/process.py", line 50, in get_landmark
    landmark = Landmark()
  File "/home/tyn/Ultralight-Digital-Human/data_utils/get_landmark.py", line 76, in __init__
    self.det_net = SCRFD('./scrfd_2.5g_kps.onnx', confThreshold=0.1, nmsThreshold=0.5)
  File "/home/tyn/Ultralight-Digital-Human/data_utils/detect_face.py", line 12, in __init__
    self.net = cv2.dnn.readNet(onnxmodel)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1057: error: (-2:Unspecified error) in function 'handleNode'
> Node [Slice@ai.onnx]:(onnx_node!Slice_25) parse error: OpenCV(4.10.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1240: error: (-215:Assertion failed) constBlobs.find(node_proto.input(i)) != constBlobs.end() in function 'parseSlice'
> 
![image](https://github.com/user-attachments/assets/d935b3ba-e9c3-4fad-86ae-a87e875398d1)

**Comment by anliyuan** [comment]
没见过这个错。。。google一下吧先
